# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-17 02:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Killer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('phase', models.IntegerField(choices=[(0, 'Sélection des participants'), (10, 'Remplissage des kills'), (20, 'Jeu en cours'), (30, 'Terminé')], default=0)),
                ('admins', models.ManyToManyField(related_name='administrating', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='kill',
            name='killer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Killer'),
        ),
        migrations.AddField(
            model_name='kill',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kill',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='kill',
            unique_together=set([('writer', 'target')]),
        ),
    ]
